export const projectContents = [
  {
    title: "Bank Application",
    technologiesUsed: "Java, Spring Boot, JUnit",
    description: [
      "Developed a Spring Boot banking application with event sourcing for efficient auditing of system and seamless rollback.",
      "Created REST APIs and performed testing using JUnit to verify functionality and error handling of each endpoint.",
      "Utilized locks to synchronize the access to a user account, ensuring data consistency across concurrent transactions",
    ],
    githubLink: "https://github.com/shreejay23/BankApplication",
    onGithub: true,
    onYouTube: false,
    youtubeLink: "",
  },
  {
    title: "Sanitation of Malicious Pickle Files",
    technologiesUsed: "Python",
    description: [
      "Developed a vulnerability detection and mitigation system for pickle file deserialization on PyTorch models serialized with Hugging Face's proprietary tools.",
      "Deployed a stack data structure to address sequential, nested, and GLOBAL opcode reuse attacks.",
      "Ensured compatibility with protocol versions 2-4 and scalability through the implementation of an allowlist.",
    ],
    githubLink: "https://github.com/shreejay23/Keeping-Our-Pickles-Edible",
    onGithub: true,
    onYouTube: false,
    youtubeLink: "",
  },
  {
    title: "NYC Airbnb: A Data Driven Stay",
    technologiesUsed: "D3.js, React.js, Python",
    description: [
      "Engineered a D3 and React-based dashboard for NYC Airbnb analysis, empowering data-driven decision-making for tenants and homeowners.",
      "Assist tenants in finding a suitable room according to their preferences and helps homeowners to adjust their pricing & provide necessary features.",
      "Enhanced interactivity among the 5 graphs on the dashboard and component reusability in a React-enabled project, facilitating users to conduct evaluations of around 1000 Airbnb listings",
    ],
    githubLink: "https://github.com/shreejay23/NYC-Airbnb",
    onGithub: true,
    onYouTube: true,
    youtubeLink: "https://www.youtube.com/watch?v=_PD3pN8OCy8",
  },
  {
    title: "PicNix: Image De-duplicating Architecture",
    technologiesUsed: "Python, Django, SQLite, React.js",
    description: [
      "Constructed a system tailored for NFTs, prioritizing cost-effective storage by avoiding storing a new image that is the exact duplicate of an image present in the database and clustering similar images for enhanced user clarity.",
      "Optimized the duplicate image detection by solely comparing incoming images with cluster centers and focusing on exact matches within the top 2 most similar clusters, resulting in the reduction of execution time by 60%.",
    ],
    githubLink: "https://github.com/shreejay23/picnix",
    onGithub: true,
    onYouTube: false,
    youtubeLink: "",
  },
  {
    title: "Key-Value Store",
    technologiesUsed: "C++",
    description: [
      "Built a key-value store using C++ with TCP/IP socket communication for reliable client-server interactions.",
      "Utilized C++ features like smart pointers and the STL containers for efficient memory management and data storage.",
    ],
    githubLink: "https://github.com/shreejay23/Key-Value-Store",
    onGithub: true,
    onYouTube: false,
    youtubeLink: "",
  },
  {
    title: "Minesweeper Game",
    technologiesUsed: "C++",
    description: [
      "Designed and implemented the classic Minesweeper game using C++ with a focus on object-oriented programming principles to create a modular and maintainable codebase.",
      "Employed efficient algorithms and data structures to optimize game performance, ensuring quick responsiveness and smooth gameplay experience.",
    ],
    githubLink: "https://github.com/shreejay23",
    onGithub: false,
    onYouTube: false,
    youtubeLink: "",
  },
  {
    title: "Language Agnostic News Summarization (LANS)",
    technologiesUsed: "Python",
    description: [
      "Constructed a text summarization system utilizing a transformer-based architecture, delivering concise summaries for multilingual news articles.",
      "Employed CNN-daily news and MLSum dataset to train Meta’s T5 small and ROBERTa RNN models.",
      "Performed evaluation with ROGUE-1 and ROGUE-L to ensure semantic coherence and relevance of generated summaries resulting in a 72% overall accuracy score.",
    ],
    githubLink:
      "https://github.com/shreejay23/Language-Agnostic-News-Summarizer",
    onGithub: true,
    onYouTube: false,
    youtubeLink: "",
  },
  {
    title: "Covid-19 Tweets Sentiment Analysis",
    technologiesUsed: "Python",
    description: [
      "Led a team to create a program using ML and NLP methods for sentiment classification in Covid-19 tweets.",
      "Designed a robust pipeline of data preprocessing and feature engineering, resulting in an 80% accuracy.",
    ],
    githubLink: "",
    onGithub: false,
    onYouTube: false,
    youtubeLink: "",
  },
];
